INSERT INTO AUTH (LOGIN, ROLE, RES) VALUES ('auravadima', 'WRITE', 'A.B.');
INSERT INTO AUTH (LOGIN, ROLE, RES) VALUES ('vasya', 'READ', 'A.K.Y.');
INSERT INTO AUTH (LOGIN, ROLE, RES) VALUES ('jdoe', 'READ', 'a.');
INSERT INTO AUTH (LOGIN, ROLE, RES) VALUES ('jdoe', 'WRITE', 'a.b.');
INSERT INTO AUTH (LOGIN, ROLE, RES) VALUES ('jrow', 'EXECUTE', 'a.b.c.');
INSERT INTO AUTH (LOGIN, ROLE, RES) VALUES ('jrow', 'EXECUTE', 'a.bc.');