UPDATE AUTH set RES='A.B.' WHERE ID=1;
UPDATE AUTH set RES='A.K.Y.' WHERE ID=2;
UPDATE AUTH set RES='a.' WHERE ID=3;
UPDATE AUTH set RES='a.b.' WHERE ID=4;
UPDATE AUTH set RES='a.b.c.' WHERE ID=5;
UPDATE AUTH set RES='a.' WHERE ID=6;